# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdHour = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdHour.setGeometry(QtCore.QRect(1, 10, 68, 61))
        self.lcdHour.setDigitCount(2)
        self.lcdHour.setObjectName("lcdHour")
        self.lcdMinute = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdMinute.setGeometry(QtCore.QRect(80, 10, 68, 61))
        self.lcdMinute.setDigitCount(2)
        self.lcdMinute.setObjectName("lcdMinute")
        self.lcdSecond = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdSecond.setGeometry(QtCore.QRect(150, 40, 41, 31))
        self.lcdSecond.setDigitCount(2)
        self.lcdSecond.setObjectName("lcdSecond")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 66, 291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lcdHomeTemp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdHomeTemp.setGeometry(QtCore.QRect(70, 162, 64, 28))
        self.lcdHomeTemp.setSmallDecimalPoint(True)
        self.lcdHomeTemp.setDigitCount(4)
        self.lcdHomeTemp.setObjectName("lcdHomeTemp")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(140, 80, 151, 111))
        self.graphicsView.setObjectName("graphicsView")
        self.lcdExtTemp = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdExtTemp.setGeometry(QtCore.QRect(70, 133, 64, 28))
        self.lcdExtTemp.setSmallDecimalPoint(True)
        self.lcdExtTemp.setDigitCount(4)
        self.lcdExtTemp.setObjectName("lcdExtTemp")
        self.lcdPressure = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdPressure.setGeometry(QtCore.QRect(70, 77, 64, 28))
        self.lcdPressure.setSmallDecimalPoint(True)
        self.lcdPressure.setDigitCount(4)
        self.lcdPressure.setObjectName("lcdPressure")
        self.lcdHumidity = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdHumidity.setGeometry(QtCore.QRect(70, 105, 64, 28))
        self.lcdHumidity.setSmallDecimalPoint(True)
        self.lcdHumidity.setDigitCount(4)
        self.lcdHumidity.setObjectName("lcdHumidity")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 80, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lblDate = QtWidgets.QLabel(self.centralwidget)
        self.lblDate.setGeometry(QtCore.QRect(200, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lblDate.setFont(font)
        self.lblDate.setObjectName("lblDate")
        self.lblWeekday = QtWidgets.QLabel(self.centralwidget)
        self.lblWeekday.setGeometry(QtCore.QRect(170, 15, 101, 17))
        self.lblWeekday.setObjectName("lblWeekday")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", ":"))
        self.label.setText(_translate("MainWindow", "Давление"))
        self.label_2.setText(_translate("MainWindow", "Влажность"))
        self.label_4.setText(_translate("MainWindow", "t на улице"))
        self.label_5.setText(_translate("MainWindow", "на балконе"))
        self.lblDate.setText(_translate("MainWindow", "30/12"))
        self.lblWeekday.setText(_translate("MainWindow", "TextLabel"))

